#dist: trusty
#sudo: required
#language: bash
#services:
#  - docker
#script:
#  - sudo docker run --privileged -it --rm -v /var/run/docker.sock:/var/run/dock.sock -v $(pwd):/root/sources -w /root/sources adalrsjr1/maverick-travis ./compile-push.sh

sudo: required

language: jvm

services:
  - docker

before_install:
  - echo 'deb http://www.lrde.epita.fr/repo/debian/ stable/' | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install spot libspot-dev -y --allow-unauthenticated
  - docker run --name mongo-build -d -p 127.0.0.1:27017:27017 mongo
  - docker run --name rabbitmq-build -d -p 127.0.0.1:5672:5672 rabbitmq:3.6-alpine

script:
 - docker login -u=$DOCKER_USER -p=$DOCKER_PASSWD
 - mvn package

after_sucess:
  - ./push-images.sh
