version: '3'
services:
  sock-shop-responsetime:
    image: adalrsjr1/maverick-analyzer-sockshop-responsetime
    networks:
      - maverick
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
    command:
      ["--spring.rabbitmq.host=rabbitmq",
       "--maverick.property.name=sockshop-responsetime",
       "--maverick.analyzer.incoming.exchange=fluentd.fanout",
	     "--maverick.analyzer.outgoing.queue=planner",
       "--maverick.property.offset=5",
       "-Xms=64m",
       "-Xmx=128m",
       "-XX:PermSize=32m",
       "-XX:MaxPermSize=64m",
       "-Djava.security.egd=file:/dev/urandom"]
