version: '3'
services:
  adaptation:
    image: adalrsjr1/maverick-executor
    networks:
      - maverick
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
      - planner
    command:
      ["--spring.rabbitmq.host=rabbitmq",
       "--executor.actions.repository=src/main/resources/actions",
       "-Xms=64m",
       "-Xmx128m",
       "-XX:PermSize=32m",
       "-XX:MaxPermSize=64m",
       "-Djava.security.egd=file:/dev/urandom"] # performance workaround
  planner:
    image: adalrsjr1/maverick-planner-file
    networks:
      - maverick
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
    command:
       ["--spring.rabbitmq.host=rabbitmq",
       "-Xms=64m",
       "-Xmx=128m",
       "-XX:PermSize=32m",
       "-XX:MaxPermSize=64m",
       "-Djava.security.egd=file:/dev/urandom"]
