version: '3'
services:
  adaptation:
    image: adalrsjr1/maverick-executor
    networks:
      - maverick
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
      - planner
    command:
      ["--spring.rabbitmq.host=rabbitmq",
       "--executor.actions.repository=src/main/resources/actions",
       "-Xms=64m",
       "-Xmx128m",
       "-XX:PermSize=32m",
       "-XX:MaxPermSize=64m",
       "-Djava.security.egd=file:/dev/urandom"] # performance workaround
  planner-repo:
    image: mongoclient/mongoclient
    networks:
      - maverick
    ports:
      - "3001:3000"
      - "27017:27017"
    volumes:
      - data-volume:/data/db
  planner:
    image: adalrsjr1/maverick-planner-mongo
    networks:
      - maverick
    depends_on:
      - planner-repo
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
    command:
      ["--spring.rabbitmq.host=rabbitmq",
       "--spring.data.mongodb.host=planner-repo",
       "--maverick.planner.nWorkers=8",
       "-Xms=64m",
       "-Xmx=128m",
       "-XX:PermSize=32m",
       "-XX:MaxPermSize=64m",
       "-Djava.security.egd=file:/dev/urandom"]
