version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    networks:
      - maverick-logging
    environment:
       #- bootstrap.memory_lock=true # bug running locally
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    networks:
      - maverick-logging
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.maverick.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_USERNAME: elastic
  fluentd:
    image: adalrsjr1/fluentd-efk
    networks:
      - maverick
      - maverick-logging
    ports:
      - "9880:9880"
      - "24224:24224"
      - "24220:24220"
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - RABBITMQ=rabbitmq
      - ELASTIC_SEARCH=elasticsearch
  rabbitmq:
    image: rabbitmq:3.6-management
    networks:
      - maverick
      - maverick-logging
    ports:
      - "15672:15672"
      - "5672:55672"
  adaptation:
    image: adalrsjr1/executor
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
      - planner
    entrypoint:
      - java
      - jar
      - maverick-executor-0.0.1-SNAPSHOT.jar
      - --spring.rabbitmq.host=rabbitmq
      - --executor.actions.repository=src/main/resources/actions
      - -Xms=64m
      - -Xmx128m
      - -XX:PermSize=32m
      - -XX:MaxPermSize=64m
      - -Djava.security.egd=file:/dev/urandom # performance workaround
  planner:
    image: adalrsjr1/planner-file
    volumes:
      - data-volume:/home/app/src/main/resources/logs
    depends_on:
      - fluentd
      - rabbitmq
      - analyzer
    entrypoint:
      - java
      - jar
      - maverick-planner-file-0.0.1-SNAPSHOT.jar
      - --spring.rabbitmq.host=rabbitmq
      - ----
      - -Xms=64m
      - -Xmx=128m
      - -XX:PermSize=32m
      - -XX:MaxPermSize=64m
      - -Djava.security.egd=file:/dev/urandom
  analyzer:

volumes:
  data-volume:
    driver: local
  esdata1:
    driver: local

networks:
  maverick:
    driver: overlay
  maverick-logging:
    driver: overlay
